services:
  v79-tiquet-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v79-tiquet-manager
    ports:
      - "3050:3050"
    environment:
      - PORT=3050
    restart: unless-stopped
